apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
  labels:
    app: app-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - name: webapp
        image: briannebeker.azurecr.io/demo-azure:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        env:
          - name: BUILD
            value: "%BUILD"